# Generated by Django 5.2.6 on 2025-09-11 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_channel_name_lower_task_task_id_task_task_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
