# Generated by Django 5.2.6 on 2025-09-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='name_lower',
        ),
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
