import type { Metadata } from "next";
import type React from "react";
import "@mantine/core/styles.css";
import "@mantine/charts/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/notifications/styles.css";
import "mantine-react-table/styles.css";
import { ColorSchemeScript, MantineProvider, Typography } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { Providers } from "@/components";

export const metadata: Metadata = {
	title: "ChatLogAnalysis",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
			</head>
			<body>
				<MantineProvider
					theme={{
						fontFamily: "Open Sans, sans-serif",
						headings: { fontFamily: "Open Sans, sans-serif" },
					}}
				>
					<Typography>
						<Providers>
							<Notifications />
							{children}
						</Providers>
					</Typography>
				</MantineProvider>
			</body>
		</html>
	);
}
