# Dockerfile for Django
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# Copy the project files
COPY . /app/

# Expose the port Django will run on
EXPOSE 8000

# Start the Django server based on the mode
CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000"]
